export const workersList = [
  {
    "number": 8764736488,
    "fname": "Rinku",
    "lname": "Kumar",
    "gender": "Male",
    "about": "This is Rinku. He works laundry.",
    "address": "Gali Number - 3, near State Bank of India, Nithari, Noida",
    "locality": "Mahanagar",
    "city": "Aligarh",
    "state": "Uttar Pradesh",
    "pincode": 245262,
    "password": "rinku@123",
    "workingDays": "4",
    "services": "laundry",
    "rating": 0.0,
    "category": "LAUNDRY",
    "reviews": [],
    "active": false
  },
  {
    "number": 8967876636,
    "fname": "Lalit",
    "lname": "Yadav",
    "gender": "Male",
    "about": "This is Lalit. He works for his livelihood with his full concentration.",
    "address": "Gali Number - 3, near State Bank of India, Nithari, Noida",
    "locality": "Kalam Nagar",
    "city": "Jaipur",
    "state": "Rajasthan",
    "pincode": 119739,
    "password": "lalit@123",
    "workingDays": "4",
    "services": "maid",
    "rating": 0.0,
    "category": "MAID",
    "reviews": [],
    "active": false
  },
  {
    "number": 8989473984,
    "fname": "Ram",
    "lname": "Khilawan",
    "gender": "Male",
    "about": "This is Ram. He works for his livelihood with his full concentration.",
    "address": "House no.534, Shanti Vihar",
    "locality": "Madhuban",
    "city": "Ghaziabad",
    "state": "Uttar Pradesh",
    "pincode": 201013,
    "password": "ram@123",
    "workingDays": "6",
    "services": "carpenter",
    "rating": 0.0,
    "category": "CARPENTER",
    "reviews": [],
    "active": false
  },
  {
    "number": 9675467567,
    "fname": "Renu",
    "lname": "Lal",
    "gender": "Female",
    "about": "This is Renu. She is a hard working woman.",
    "address": "House no.534, Shanti Vihar",
    "locality": "Shastri Nagar",
    "city": "Meerut",
    "state": "Uttar Pradesh",
    "pincode": 252322,
    "password": "renu@123",
    "workingDays": "6",
    "services": "cook",
    "rating": 0.0,
    "category": "COOK",
    "reviews": [],
    "active": false
  },
  {
    "number": 9878673353,
    "fname": "Arun",
    "lname": "Kumar",
    "gender": "Male",
    "about": "This is Arun. He is a milkman and is doing this service since 20 years in his locality.",
    "address": "Gali Number - 3, near State Bank of India, Nithari, Noida",
    "locality": "Nithari",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "pincode": 110025,
    "password": "arun@123",
    "workingDays": "7",
    "services": "Milkman",
    "rating": 0.0,
    "category": "MILKMAN",
    "reviews": [],
    "active": false
  },
  {
    "number": 9879874944,
    "fname": "Shanti",
    "lname": "Devi",
    "gender": "Female",
    "about": "This is Shanti. She is a hard working woman.",
    "address": "Gali Number - 5, jail road",
    "locality": "Anand Nagar",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "pincode": 226012,
    "password": "shanti@123",
    "workingDays": "5",
    "services": "gardener",
    "rating": 0.0,
    "category": "GARDNER",
    "reviews": [],
    "active": false
  },
  {
    "number": 9897843677,
    "fname": "Krishna",
    "lname": "Kumar",
    "gender": "Male",
    "about": "This is Krishna. He studied electricals very well and he is proficient in it.",
    "address": "Gali Number - 3, near State Bank of India, Nithari, Noida",
    "locality": "Aashiyana",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "pincode": 201222,
    "password": "krishna@123",
    "workingDays": "5",
    "services": "electrician",
    "rating": 0.0,
    "category": "ELECTRICIAN",
    "reviews": [],
    "active": false
  }
]

export const customerList = [
  {
    fname: "Sachin",
    lname: "Singhal",
    gender: "Male",
    number: "8896754995",
    email: "sachins@gmail.com",
    city: "Lucknow",
    state: "Uttar Pradesh"
  },
  {
    fname: "Vansh",
    lname: "Jain",
    gender: "Male",
    number: "7665796854",
    email: "vansh98786@gmail.com",
    city: "Noida",
    state: "Uttar Pradesh"
  },
  {
    fname: "Dikshansh",
    lname: "Kumar",
    gender: "Male",
    number: "9967558964",
    email: "dikshanshk@gmail.com",
    city: "Jaipur",
    state: "Rajasthan"
  },
  {
    fname: "Digvijay",
    lname: "Gagneja",
    gender: "Male",
    number: "6387677688",
    email: "dgvijay@gmail.com",
    city: "Bhopal",
    state: "Madhya Pradesh"
  },
  {
    fname: "Farhan",
    lname: "Shaikh",
    gender: "Male",
    number: "7866535789",
    email: "mdfarhan@gmail.com",
    city: "Jaunpur",
    state: "Uttar Pradesh"
  },
  {
    fname: "Divya",
    lname: "Sehgal",
    gender: "Female",
    number: "9985674355",
    email: "dsehgal@gmail.com",
    city: "Noida",
    state: "Uttar Pradesh"
  }
]